filecoin-project/venus-wallet

core/msg_router.go
method for customization of SupportedMsgtypes
=> ResigtSupportedMsgTypes

api/remotecli/httpparse/parse.go, api/remotecli/httpparse/parse_test.go, crypto/aes/aes128.go, storage/keymix.go, storage/strategy/strategy.go, storage/wallet/wallet.go
feat: strategy level 0 allow wallet full permisson
=> fix: aes encrypt

storage/keymix.go
=> make wallet unlock usable after restart wallet

cmd/daemon.go, cmd/wallet/main.go, storage/sqlite/key_store.go, storage/sqlite/short_address.go, storage/wallet/wallet.go, wallet_event/listenevent.go
1. make setting address flag in correspondence with other venus modules
2. make address persistence have no relationship with network type
=> make setting address flag in correspondence with other venus modules

storage/sqlite/key_store.go, storage/wallet/wallet.go
=> fix: remove debug output

Makefile, dockerfile
fix https://github.com/filecoin-project/venus/issues/4999
update dependencies of ddl from base docker image
=> chore #4999 : venus-wallet : update dependencies of ddl

docs/en/getting-started-local.md, docs/en/getting-started-remote.md, docs/zh/快速上手[本地].md, docs/zh/快速上手[远程].md
fix https://github.com/filecoin-project/venus/issues/5020
=> docs: migrate docs from venus-docs

.github/workflows/build_upload.yml
only trigger auto publish on PR is merged
原因及方案说明: https://github.com/filecoin-project/venus/issues/5090
=> chore: git action: only trigger auto publish on PR merged

cmd/wallet/main.go
resolve https://github.com/filecoin-project/venus/issues/5001
As described in title
=> style: unify network name

.github/workflows/build_upload.yml, .github/workflows/docker_image.yml, .github/workflows/go.yml, build/builder.go, cli/helper/helper.go
resolve https://github.com/filecoin-project/venus/issues/5002
=> ci: 拆分git工作流/split git workflow

common/version.go, go.mod, go.sum, version/version.go
=> chore: bump version to v1.7.0 (#100)

Makefile
involve https://github.com/filecoin-project/venus/issues/5267
- fix: rm BUILD_DEPS
=> fix: rm BUILD_DEPS

cmd/wallet/main.go, go.mod, go.sum, version/version.go
=> chore: bump version to 1.8.0-rc2

go.mod, go.sum, version/version.go
close nil
用于准备发布v1.8.0-rc3
升级venus， venusgateway的依赖包。 修改版本信息
=> chore: prepare for v1.8.0-rc3, upgrade venus, venus-gateway go mod.

Makefile, docker/script/init.sh
involve https://github.com/filecoin-project/venus/issues/5489
=> chore: migrate docker script

filemgr/config_manager.go, filemgr/fs_test.go
close https://github.com/filecoin-project/venus/issues/5523
=> fix: SignFilter is nil

go.mod, go.sum
=> chore: upgrade venus-related ref version to 1.9.0

Makefile, cli/wallet.go, crypto/delegated.go, crypto/key.go, crypto/key_test.go, example/main.go, filemgr/fs_test.go, filemgr/jwt.go, integration_test/builder.go
=> feat: support delegated address

go.mod, go.sum, version/version.go
=> chore: bump version to v1.10.0-rc2

crypto/delegated.go, crypto/key_test.go, storage/sqlite/key_types.go, storage/wallet/wallet.go
=> fix: failed to save delegated address

CHANGELOG.md, go.mod, go.sum, version/version.go
=> chore: bump version to v1.10.1

CHANGELOG.md, Makefile, go.mod, go.sum
=> Pre/v1.11 / 合并预发布分支 

version/version.go
=> chore: bump up version / 更新版本到 v1.11.0-rc1

storage/wallet/sign_type.go
close filecoin-project/venus#5922
=> fix: panic when ParseObj is nil

CHANGELOG.md, go.mod, go.sum, storage/wallet/sign_type.go, version/version.go
=> Chore/bump up version to v1.11.0

config/provider.go
错误配置，`admin` 缺少 `"`。
```
[APIRegisterHub]
SupportAccounts = [admin]
```
改动前错误输出：
```
2023-05-24T17:47:09.509+0800    INFO    main    cmd/daemon.go:51        wallet repo: /Users/haoziyan/.venus_wallet
opening fs repo: While parsing config: toml: incomplete number
```
改动后错误输出：
```
2023-05-24T17:47:53.448+0800    INFO    main    cmd/daemon.go:51        wallet repo: /Users/haoziyan/.venus_wallet
opening fs repo: toml: line 25 (last key "APIRegisterHub.SupportAccounts"): expected value but found "admin" instead
```
=> opt: use toml lib to decode config

cli/auth.go
=> fix: correctly generate token of api

cli/auth.go, cmd/rpc.go, go.mod, go.sum
close https://github.com/filecoin-project/venus/issues/6002
=> fix: permission not found

docs/zh/快速上手[远程].md
=> 更新一些错误的命令 / update some outdated command

.github/workflows/go.yml
close
ref https://github.com/filecoin-project/venus-wallet/pull/148#issuecomment-1661534292
=> chore(CI): ignore docs

Makefile, docs/en/getting-started-remote.md, docs/zh/快速上手[本地].md, docs/zh/快速上手[远程].md, docs/zh/订单过滤器.md
=> chore: update docs

cli/auth.go
close
考虑到 sign、export、del 等命令直接使用时都需要进行密码验证
在使用 `auth api-info`  命令生成具有 admin/sign 权限的 token 时，也应该进行密码验证。
=> feat: add password verification for api-info command

CHANGELOG.md, go.mod, go.sum, version/version.go
=> chore: bump version to v1.14.0

CHANGELOG.md, go.mod, go.sum, version/version.go
=> chore: bump version to v1.15.0
